### ISSUE TITLE
Add wlan profiles to see if Wi-Fi Cards have connect to Wi-Fi

### ISSUE THREAD

**Issue by GalactusX** [newhandle/Meta-Blue#1]
#Example
$wlan = netsh.exe wlan show profiles name=*
$wlanout = $wlan | Select-String -Pattern 'SSID name'
$Profilename = ($wlanout -split ";").trim() -replace '"'

**Comment by newhandle** [comment]
Added HistoricalWifiConnections and VisibleWifiConnections
