### ISSUE TITLE
Add detect system type feature

### ISSUE THREAD

**Issue by GalactusX** [newhandle/Meta-Blue#2]
#Example
ForEach ($Computer in $Computers)
{
	$PING = ping $Computer -n 1
	$PING = $PING | Select-String "TTL="
	$PING = [string]$PING
	$PING = $PING.Split(" ")
	$DEAD = Test-Connection -ComputerName $Computer -Count 1
	if ( $PING[-1] -le "TTL=128" -and $PING[-1] -ge "TTL=115" )
	{
		Write-Host "Found a Windows system: $Computer"
		$Computer >> "C:\Users\$ENV:Username\Desktop\Windows_Computers.txt"
	}
	if ( $PING[-1] -le "TTL=64" -and $PING[-1] -ge "TTL=45" )
	{
		Write-Host "Found a NIX Machine: $Computer"
		$Computer >> "C:\Users\$ENV:Username\Desktop\NIX_Computers.txt"
	}
	if ( $PING[-1] -le "TTL=255" -and $PING[-1] -ge "TTL=230" )
	{
		Write-Host "Found a infastructure device: $Computer"
		$Computer >> "C:\Users\$ENV:Username\Desktop\INF_Device_Computers.txt"
	}
	if ( $DEAD.StatusCode -eq "0" )
	{
		# Write-Host "Machine is up but might be using IPv6"
	}
	elseif ( $DEAD.Statuscode -ne "0" )
	{
		Write-Host "Computer: $Computer is not responding to ping requests" -ForeGroundColor Red
		$Computer >> "C:\Users\$ENV:Username\Desktop\Non-Responsive_Computers.txt"
	}
}

**Comment by newhandle** [comment]
Added this functionality.
